# Documentation in https://dependabot.com/docs/config-file/
version: 1
update_configs:
  - package_manager: "java:maven"
    directory: "/"
    update_schedule: "daily"
    allowed_updates:
      - match:
          update_type: "security"
    default_labels:
      - "area/dependencies"
  - package_manager: "docker"
    directory: "/dockerfiles/che"
    update_schedule: "daily"
    allowed_updates:
      - match:
          update_type: "security"
    default_labels:
      - "area/dependencies"
  - package_manager: "docker"
    directory: "/dockerfiles/keycloak"
    update_schedule: "daily"
    allowed_updates:
      - match:
          update_type: "security"
    default_labels:
      - "area/dependencies"
  - package_manager: "docker"
    directory: "/dockerfiles/postgres"
    update_schedule: "daily"
    allowed_updates:
      - match:
          update_type: "security"
    default_labels:
      - "area/dependencies"
